backend:
  name: git-gateway
  branch: master
media_library:
  name: cloudinary
  config:
    cloud_name: dklongley
    api_key: 325856925759214
    multiple: true


publish_mode: editorial_workflow
#logo_url: https://www.manfredcostahomes.com/img/mch-logo-wide-40.svg

media_folder: "site/static/img" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        field: {label: Image, name: image, widget: "image"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: "string"}
          - {label: Subtitle, name: subtitle, widget: "string"}
          - {label: Image, name: image, widget: "image"}
          - {label: "Blurb", name: blurb, widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "SubHeading", name: "subheading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Reasons", name: "reasons", widget: "list", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "SubHeading", name: "subheading", widget: "text"},
              {label: "Benefits", name: "benefits", widget: "list", fields: [
              {label: "Benefit", name: "benefit", widget: "text"}]}]}
          - {label: "Possibilities", name: "possibilities", widget: "list", fields: [
              {label: "Heading", name: "heading", widget: "text"},
              {label: "SubHeading", name: "subheading", widget: "text"},
              {label: "Possible", name: "possible", widget: "markdown"}]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/contact/index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Type, name: type, widget: "hidden",default: "contact"}
          - {label: Title, name: title, widget: "hidden", default: "contact"}
          - {label: Heading, name: heading, widget: "string"}
          - {label: Image, name: image, widget: "image"}
          - {label: Body, name: body, widget: "markdown"}
          - label: Contact Entries
            name: contact_entries
            widget: "list"
            fields:
              - label: Heading
                name: heading
                widget: "string"
              - label: Text
                name: text
                widget: "text"
      - file: "site/content/get-started/index.md"
        label: "Get Started"
        name: "get-started"
        fields:
          - {label: Type, name: type, widget: "hidden", default: "get-started"}
          - {label: Title, name: title, widget: "hidden", default: "get-started"}
          - {label: Heading, name: heading, widget: "string"}
          - {label: Subtitle, name: subtitle, widget: "string"}
          - {label: Image, name: image, widget: "image"}
          - {label: Body, name: body, widget: "markdown"}
      - file: "site/content/recent-work/index.md"
        label: "Recent work"
        name: "recent-work"
        fields:
          - {label: Type, name: type, widget: "hidden", default: "recent-work"}
          - {label: Title, name: title, widget: "hidden", default: "recent-work"}
          - {label: Heading, name: heading, widget: "string"}
          - {label: Subtitle, name: subtitle, widget: "string"}
          - {label: Image, name: image, widget: "image"}
          - {label: Body, name: body, widget: "markdown"}
      - file: "site/content/why-cloud-hosted/index.md"
        label: "Why Cloud Hosted"
        name: "why-cloud-hosted"
        fields:
          - {label: Type, name: type, widget: "hidden", default: "why-cloud-hosted"}
          - {label: Title, name: title, widget: "hidden", default: "why-cloud-hosted"}
          - {label: Title, name: title, widget: "string"}
          - {label: Subtitle, name: subtitle, widget: "string"}
          - {label: Image, name: image, widget: "image"}
          - {label: Body, name: body, widget: "markdown"}
